name: Templates

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  template:
    name: Apply templates
    runs-on: ubuntu-22.04
    strategy:
        fail-fast: false
        matrix:
          repository:
            - samuelallan72/test-target
    steps:
      - name: Checkout ${{ matrix.repository }}
        uses: actions/checkout@v4
        with:
            repository: ${{ matrix.repository }}

      - name: Checkout automation
        uses: actions/checkout@v4
        with:
          path: automation-repo

      - name: Apply templates
        run: python3 template.py -r ${{ matrix.repository }} -p ../
        working-directory: automation-repo

        # this working dir and cleanup weirdness is to workaround lack of support for working-directory for create-pull-request
      - name: Clean up automation code
        run: rm -rf automation-repo

      - name: Show diff
        run: |
          git status
          git add -A
          git diff
          git reset

      - name: Create pull request
        uses: canonical/create-pull-request@main
        with:
          upsert: true  # Allow update PRs
          base: main
          github-token: ${{ secrets.PR_TOKEN }}
          branch-name: PR_id-update
          repository: ${{ matrix.repository }}
          title: "update templates"
          body: "This pull request was generated by automation"
          commit-message: |
            This commit was autogenerated
